# 服务端口号
server:
  port: 8080
# 数据库地址
datasource:
  url: localhost:3306/test_db

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?
      useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
    hikari:
      max-lifetime: 1770000
      maximum-pool-size: 10
# 整合mybatis
mybatis:
  type-aliases-package: com.sckj.springboot.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名法
  mapper-locations: #mybatis的位置
    - classpath:mapper/*.xml