server:
  port: 8888

# 单个配置
#person:
#  last-name: 吴发明
#  age: 21
#  birth: 2000/03/08

# 配置数组
city:
  cityList:
    北京,上海,成都

# 集合数据配置
person:
  last-name: 杜鹏
  age: 34
  birth: 2021/03/08
  lists:
    - 吴发明
    - 冯家超
    - 王力勇
    - 李杰