#server:
#  port: 8001
# 配置微服务地址
url:
  #  订单微服务地址
  orderUrl: http://localhost:8002
  #  用户微服务地址
  userUrl: http://localhost:8003
  #  购物车微服务地址
  shoppingUrl: http://localhost:8004
spring:
  profiles:
    active:
      - pro